<craft>
    <parameter name="size" type="int" default="1"/>
    <parameter name="length" type="int" default="30"/>

    <group>
        <script>
            function main() {
                // Handle
                var size = params.size;
                var length = params.length;
    
                // handles minimum length
                if (length < 15) { length = 15; }
    
                var handleDiff, h;
    
                // parts
                handleDiff = cube({
                    size: [2, 35, 4],
                    center: true
                }).translate([0, -25, 2]);
    
                h = cylinder({
                    r1: 1.5,
                    r2: 2,
                    h: length,
                    fn: 6
                }).scale([1, 0.4, 1]);
    
                // handle positioning
                h = h.rotateX(95);
                h = h.translate([0, -12, 3]);
    
                h = difference(
                    h,
                    union(
                        handleDiff.translate([2, 0, 0]).rotateZ(1),
                        handleDiff.translate([-2, 0, 0]).rotateZ(-1)
                    ),
                    sphere(4).scale([1, 2, 1]).translate([0, -14, 1.5]).rotateX(10)
                );
    
                return h.scale(size);
            }
        </script>
    
        <script>
            function main() {
                // Neck
                var size = params.size;
    
                var curve, neck, neckDiff;
    
                // parts
                curve = cylinder({
                    r: 8,
                    h: 20
                }).rotateX(90).translate([0, 10, 14]);
    
                neck = intersection(
                    sphere(10),
                    curve
                );
    
                neckDiff = cube({
                    size: [5, 20, 10],
                    center: true
                }).translate([0, -15, 0]);
    
                // transition to handle
                neck = neck.translate([0, -13, -1]);
                neck = rotate([205, 180, 180], neck);
                
                neck = difference(
                    neck,
                    neck.rotateX(-10).translate([0, 2, -3]),
                    union(
                        neckDiff.translate([3.5, 0, 0]).rotateZ(1),
                        neckDiff.translate([-3.5, 0, 0]).rotateZ(-1),
                        cube({
                            size: [5, 3, 3],
                            center: true
                        }).translate([0, -20, -3])
                    ),
                    sphere(4).scale([1, 2, 1]).translate([0, -14, 1.5]).rotateX(10)
                ); 
    
                return neck.scale(size);
            }
        </script>
    
        <script>
            function main() {
                // Scoop
                var size = params.size;
                
                var scoopHead, diff, scoopEnd;
                 
                // parts
                diff = cylinder({
                    r: 8,
                    h: 20
                });
    
                // transformations
                diff = diff.rotateX(90).translate([0, 10, 14]);
    
                // creates scoop base
                scoopHead = intersection(
                    sphere(10),
                    diff
                ).rotateY(180);
    
                // hollows out scoop parts
                scoopHead = difference(
                    scoopHead,
                    scoopHead.translate([0, 0, 1])
                );
    
                return scoopHead.translate([0, 0, 10]).rotateX(10).scale(size);
            }
        </script>
    </group>

</craft>